### ISSUE TITLE
Configuration Help Please

### ISSUE THREAD

**Issue by ChrstnMgcn** [Jako/CustomRequest#44]
This works fine
https://domain.com/school-landing/999999/ to https://domain.com/school-landing/?school_code=999999

But is it possible to have the configurations at root level? This is what I'm looking to do:

https://domain.com/999999/ to https://domain.com/school-landing/?school_code=999999

https://domain.com/999999/profiles/ to https://domain.com/school-landing/profiles/?school_code=999999

https://domain.com/999999/coaches/ to https://domain.com/school-landing/coaches/?school_code=999999

**Comment by Jako** [comment]
I don't think that you can use the 999999 as the first part of the url, since CustomRequest strips the url from left to right.

Is it possible to have the school code at the end? Then you can work with the pagination example: https://jako.github.io/CustomRequest/examples/#pagination

You can redirect the following somehow for every not found url:

https://domain.com/school/999999/ to https://domain.com/?school_code=999999

https://domain.com/profiles/school/999999/ to https://domain.com/profiles/?school_code=999999

https://domain.com/coaches/school/999999/ to https://domain.com/coaches/?school_code=999999

If not, you have to create an own plugin that detects a possible school code in a not found URL and strips that from the detected url and uses the remaining URL to identify the resource where the user is forwarded to later.

**Comment by ChrstnMgcn** [comment]
Thanks for getting back to me so quickly! Unfortunately for this purpose I think the school code will need to be in the beginning (and may change to the school name instead). I'll work on a custom plugin instead. Thanks for the direction on how to do that!

**Comment by Jako** [comment]
The important part where you have to patch the CustomRequest code is this:

https://github.com/Jako/CustomRequest/blob/master/core/components/customrequest/src/CustomRequest.php#L341-L387

You don't need the configuration part and most of the other parts of CustomRequest in your code.

**Comment by ChrstnMgcn** [comment]
Got it, thanks again!

**Comment by Jako** [comment]
Also you need the method in this line to get the resource id by the alias: https://github.com/Jako/CustomRequest/blob/master/core/components/customrequest/src/CustomRequest.php#L306

**Comment by ChrstnMgcn** [comment]
I need to redirect if an invalid school code is used, but I have the plugin working with the following.

```
<?php 
$request = trim($_SERVER['REQUEST_URI'], '/');
list($school, $page) = explode("/",$request);

if($school) {
    if(!is_numeric($school)) { return; }
    $_GET['school_code'] = $school;
    $resourceId = 9;
}
if($page) {
    $pageInfo = $modx->getObject('modResource', array('alias' => "$page", 'parent' => "$resourceId"));
    if($pageInfo) {
        $resourceId = $pageInfo->get('id');
    }
}

$modx->sendForward($resourceId);

return true;
?>
```

**Comment by Jako** [comment]
You just have to return at the end of the plugin.

```php
<?php
$request = trim($_SERVER['REQUEST_URI'], '/');
list($school, $page) = explode('/', $request);

if ($school) {
    if (!is_numeric($school)) {
        return;
    }
    // Some method to detect wether the school code is valid 
    if (!$modx->getCount('schooldatabaseclass', ['schoolname' => $school])) { 
        return;
    }
    $_GET['school_code'] = $school;
    $resourceId = 9;
}
if ($page) {
    $resourceId = $modx->findResource($page);
}
if ($resourceId) {
    $modx->sendForward($resourceId);
}

return;
```
